server:
  port: 9002

# 配置集群
eureka:
  dashboard:
    enabled: true
    path: /
  instance:
    hostname: ClusterEurekaServerB

  client:
    enabled: true
    service-url:
      # 配置客户端所交互的Eureka Server的地址（Eureka Server集群中每一个Server其实相对于其它Server来说都是Client）
      # 集群模式下，defaultZone应该指向其它Eureka Server，如果有更多其它Server实例，逗号拼接即可
      # 注意，这里的 /eureka/ 不能随意修改，是内部的自己启的一个 controller，他们会用 http get 请求来自动同步
      defaultZone: http://ClusterEurekaServerA:9001/eureka/
    register-with-eureka: true
    fetch-registry: true
