server:
  port: 9002

# 配置集群
eureka:
  dashboard:
    enabled: true
    path: /
  instance:
    hostname: Cluster-Eureka-ServerB
    # 在旧版本的 Eureka 显示以 spring.application.name 为优先，在新版本的 Eureka 显示以 eureka.instance.appname 为优先。
    # 因此，不要使用 appname，以免未来切换注册中心给自己找麻烦。
  #    appname: cluster-server
  client:
    enabled: true
    service-url:
      defaultZone: http://Cluster-Eureka-ServerA:9001/eureka/
    register-with-eureka: true
    fetch-registry: true
