// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: D/user.proto

package com.eor.proto.pojo;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double money = 3;</code>
   * @return The money.
   */
  double getMoney();

  /**
   * <code>bool live = 4;</code>
   * @return The live.
   */
  boolean getLive();
}
