// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: D/user.proto

package com.eor.proto.pojo;

public final class Users {
  private Users() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014D/user.proto\022\010tutorial\"=\n\004User\022\n\n\002id\030\001" +
      " \001(\003\022\014\n\004name\030\002 \001(\t\022\r\n\005money\030\003 \001(\001\022\014\n\004liv" +
      "e\030\004 \001(\010B\035\n\022com.eor.proto.pojoB\005UsersP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Money", "Live", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
