// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.eor.proto.vo;

public interface TagsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protoRoot.Tags)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string tag = 1;</code>
   * @return A list containing the tag.
   */
  java.util.List<java.lang.String>
      getTagList();
  /**
   * <code>repeated string tag = 1;</code>
   * @return The count of tag.
   */
  int getTagCount();
  /**
   * <code>repeated string tag = 1;</code>
   * @param index The index of the element to return.
   * @return The tag at the given index.
   */
  java.lang.String getTag(int index);
  /**
   * <code>repeated string tag = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tag at the given index.
   */
  com.google.protobuf.ByteString
      getTagBytes(int index);
}
