// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.eor.proto.vo;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoRoot_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoRoot_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoRoot_Tags_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoRoot_Tags_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\tprotoRoot\"L\n\004User\022\n\n\002id\030\001 " +
      "\001(\003\022\014\n\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\035\n\004tags\030\004" +
      " \003(\0132\017.protoRoot.Tags\"\023\n\004Tags\022\013\n\003tag\030\001 \003" +
      "(\tB \n\020com.eor.proto.voB\nUserProtosP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protoRoot_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protoRoot_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoRoot_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Tags", });
    internal_static_protoRoot_Tags_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protoRoot_Tags_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoRoot_Tags_descriptor,
        new java.lang.String[] { "Tag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
