// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.eor.proto.vo;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protoRoot.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 3;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>repeated .protoRoot.Tags tags = 4;</code>
   */
  java.util.List<com.eor.proto.vo.Tags> 
      getTagsList();
  /**
   * <code>repeated .protoRoot.Tags tags = 4;</code>
   */
  com.eor.proto.vo.Tags getTags(int index);
  /**
   * <code>repeated .protoRoot.Tags tags = 4;</code>
   */
  int getTagsCount();
  /**
   * <code>repeated .protoRoot.Tags tags = 4;</code>
   */
  java.util.List<? extends com.eor.proto.vo.TagsOrBuilder> 
      getTagsOrBuilderList();
  /**
   * <code>repeated .protoRoot.Tags tags = 4;</code>
   */
  com.eor.proto.vo.TagsOrBuilder getTagsOrBuilder(
      int index);
}
