server:
  port: 9001
spring:
  application:
    # ???????????????????????????
    name: cluster-server

# ????
eureka:
  instance:
    hostname: Cluster-Eureka-Server01
    # ????? Eureka ??? spring.application.name ????????? Eureka ??? eureka.instance.appname ????
    # ??????? appname??????????????????
#    appname: cluster-server
  client:
    enabled: true
    service-url:
      defaultZone:
        - http://Cluster-Eureka-Server01:9002/eureka
    register-with-eureka: true
    fetch-registry: true
