




spring:
  cloud:
    gateway:
#      discovery:
#        # ???????http://Gateway_HOST:Gateway_PORT/???serviceId/**????????????????
#        locator:
#          enabled: true
#          # ???? service-id
#          lowerCaseServiceId: true
      routes:
        # ????
        - id: ruoyi-auth
          uri: lb://ruoyi-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

