/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An explanation about the purpose of this instance.
 */
export type TheIdSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNameSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheAgeSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFirstAnyOfSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheSecondAnyOfSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheThirdAnyOfSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheTagsSchema = (TheFirstAnyOfSchema | TheSecondAnyOfSchema | TheThirdAnyOfSchema)[];

/**
 * The root schema comprises the entire JSON document.
 */
export interface TheRootSchema {
  user: TheUserSchema;
  [k: string]: unknown;
}
/**
 * An explanation about the purpose of this instance.
 */
export interface TheUserSchema {
  id: TheIdSchema;
  name: TheNameSchema;
  age: TheAgeSchema;
  tags: TheTagsSchema;
  [k: string]: unknown;
}
